name: Citation Intelligence Bot

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  citation-bot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Activate venv
        run: echo "/home/swilson/actions-runner-env/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pip install -q -r requirements.txt

      - name: Run Citation bot
        env:
          PYTHONPATH: citation_bot
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          LOOKBACK_PERIOD: 'week'
        run: python citation_bot/citation_bot.py
